name: Build and Push Multi-Platform Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - linux/amd64
#          - linux/arm/v7
          - linux/arm64
#          - linux/arm/v6
        include:
          - platform: linux/amd64
            build_from: ghcr.io/home-assistant/amd64-base-python
            arch_name: amd64
#          - platform: linux/arm/v7
#            build_from: ghcr.io/home-assistant/armv7-base-python
#            arch_name: armv7
          - platform: linux/arm64
            build_from: ghcr.io/home-assistant/aarch64-base-python
            arch_name: aarch64
#          - platform: linux/arm/v6
#            build_from: ghcr.io/home-assistant/armhf-base-python
#            arch_name: armhf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            BUILD_FROM=${{ matrix.build_from }}
            TARGETPLATFORM=${{ matrix.platform }}
          tags: |
            oideibrett/image-${{ matrix.arch_name }}-matterflow:latest
            oideibrett/image-${{ matrix.arch_name }}-matterflow:${{ github.sha }}
            oideibrett/image-${{ matrix.arch_name }}-matterflow:${{ github.event.release.tag_name }}
