name: Build and Push Multi-Platform Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/armv7] # Specify the platforms you want to build for
        include:
          - platform: linux/amd64
            build_from: ghcr.io/home-assistant/amd64-base-python
            target_platform: amd64
          - platform: linux/armv7
            build_from: ghcr.io/home-assistant/armv7-base-python
            target_platform: armv7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            TARGETPLATFORM=${{ matrix.target_platform }}
            BUILD_FROM=${{ matrix.build_from }}
          tags: |
            oideibrett/matterflow:latest
            oideibrett/matterflow:${{ github.sha }}
